### ISSUE TITLE
Case of registered names

### ISSUE THREAD

**Issue by uschuster** [remobjects/pascalscript#122]
The case of registered names and keywords for classes, methods, properties and so on are partly completely UPPERCASE / do not match the case of the (Delphi) stuff they are mapped to.

Actual code in uPSC_stdctrls.pas:
```Delphi
procedure SIRegisterTGROUPBOX(Cl: TPSPascalCompiler);
begin
  with Cl.AddClassN(cl.FindClass('TCUSTOMGROUPBOX'), 'TGROUPBOX') do
  begin
    RegisterProperty('CAPTION', 'String', iptrw);
    RegisterProperty('COLOR', 'TColor', iptrw);
```

Expected code in uPSC_stdctrls.pas:
```Delphi
procedure SIRegisterTGROUPBOX(Cl: TPSPascalCompiler);
begin
  with Cl.AddClassN(cl.FindClass('TCustomGroupBox'), 'TGroupBox') do
  begin
    RegisterProperty('Caption', 'string', iptrw);
    RegisterProperty('Color', 'TColor', iptrw);
```

We expose the registered stuff to our users and so they see a lot of UPPERCASE stuff that SHOUTS. We are going to fix this in a fork soon.

**Comment by carlokok** [comment]
If you send a pull request for that I'll amke sure to merge it
