### ISSUE TITLE
division of variant variables

### ISSUE THREAD

**Issue by ifermc** [remobjects/pascalscript#141]
Please correct division of variant variables. It used to work correctly but in new version it does not any more. It is lethal, because old working scripts fail now.

var x,y :variant;
begin
  x:=23;
  y:=x/200;
end.

y should be 0.115 but it is zero because the result obviously is also integer.

**Comment by carlokok** [comment]
not sure what you mean, nothing in regards to variants has changed in over 6 years

**Comment by ifermc** [comment]
In my typical script I am making calculation as follows:

      v:=Pi * power(Species['DBH_cm']/200,2) * Species['StemNumber_1'];

Species['DBH_cm'] just takes variant value from the database.

These scripts used to return correct values. In last e.g. 1-2 year it started to return zero values unless I change scripting:

      v:=Pi * power(Species.ValueAsFloat['DBH_cm']/200,2) * Species['StemNumber_1'];

I will go to the archive and try to find old executables on whichI can demonstrate it. But for that I need my colleague who is currently on vacation.

The content of the problem has been described in my previous post. When the integer is divided then the result is again integer i.e. floating point division using / is equal to integer division using div.

var x,y :variant; 
begin
  x:=23;
  y:=x/200;
end.

The result is the same if x is declared as integer instead of variant and y as double instead of variant:
var y :double;
    x :integer; 
begin
  x:=23;
  y:=x/200;
end.

y is always equal to zero. And this is of wrong.

The only thing which helps is retyping of variable to double. Then the result is correct. But this is not always possible to do.
var y :double;
    x :integer; 
begin
  x:=23;
  y:=double(x)/200;
end.

Hopefully it might be possible for you to change the / division operation in that way that all participating numbers are automatically assumed to be floating point as well as the resulted variable.

Other than that we evaluate Pascal scripts very high. It is fantastic tool especially with its possibility of defining my own classes and functions.

**Comment by carlokok** [comment]
Right. What I'm saying is that we had this behavior for ever, it's not a recent change and people depend on this behavior as PS has always done this. The only workaround I can offer is to replace 200 with 200.0

On 17 August 2016 09:22:04 CEST, ifermc <notifications@github.com> wrote:
>In my typical script I am making calculation as follows:
>
>      v:=Pi * power(Species['DBH_cm']/200,2) * Species['StemNumber_1'];
>
>Species['DBH_cm'] just takes variant value from the database.
>
>These scripts used to return correct values. In last e.g. 1-2 year it
>started to return zero values unless I change scripting:
>
>v:=Pi * power(Species.ValueAsFloat['DBH_cm']/200,2) *
>Species['StemNumber_1'];
>
>I will go to the archive and try to find old executables on whichI can
>demonstrate it. But for that I need my colleague who is currently on
>vacation.
>
>The content of the problem has been described in my previous post. When
>the integer is divided then the result is again integer i.e. floating
>point division using / is equal to integer division using div.
>
>var x,y :variant; 
>begin
>  x:=23;
>  y:=x/200;
>end.
>
>The result is the same if x is declared as integer instead of variant
>and y as double instead of variant:
>var y :double;
>    x :integer; 
>begin
>  x:=23;
>  y:=x/200;
>end.
>
>y is always equal to zero. And this is of wrong.
>
>The only thing which helps is retyping of variable to double. Then the
>result is correct. But this is not always possible to do.
>var y :double;
>    x :integer; 
>begin
>  x:=23;
>  y:=double(x)/200;
>end.
>
>Hopefully it might be possible for you to change the / division
>operation in that way that all participating numbers are automatically
>assumed to be floating point as well as the resulted variable.
>
>Other than that we evaluate Pascal scripts very high. It is fantastic
>tool especially with its possibility of defining my own classes and
>functions.
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remobjects/pascalscript/issues/141#issuecomment-240333568

-- 
Carlo Kok
RemObjects Software

**Comment by ifermc** [comment]
Unfortunately this type of workarounds is not very helpful. One may forget, and scripts are there for those who are not real programmers but still want to add some functionality to the application. I believe that such basic thing as division should work properly.

I am sure that some years ago the database calculations which I described in my previous post worked. But perhaps it was caused by some other reason. I will come back to it.

**Comment by ifermc** [comment]
In addition, I think that it's quite a wild assumption that someone depends on wrong division arithmetic. Anyone who wants integer division would most likely use DIV operator.

**Comment by FHannes** [comment]
This behavior has indeed existed in PS forever, but it is also quite common in other languages for the division of two integer values to return an integer value. Something I assume is rooted in the fact that integer division is much cheaper than floating point division to perform. If one of the values is a floating point value, it should perform floating point division as I recall. That is why you have to append .0 to one of the values in your formula or cast one of the integers to a floating point type. In my opinion, this is not a bug.

**Comment by ifermc** [comment]
Good to know. I work my whole working life with Delphi, and it works differently than your Pascal script. 

I will double check my old executables (Delphi 6) where it for some reason worked differently.

But anyway, thank you for swift response. Pascal scripts are very helpful.

**Comment by carlokok** [comment]
indeed, i should have been more clear, when the left or right is a float it does float division, else it's integer.

**Comment by ifermc** [comment]
I just looked to the definition of other pascals including general pascal description on Wikipedia. Everywhere it says that / is real division and the result is real number. Seems that your Pascal scripts is an exception among pascals.

**Comment by carlokok** [comment]
Oxygene has the same behavior (unless Delphi mode is explicitly said), but yes other pascal variants do float for /.

**Comment by ifermc** [comment]
That would be really great if Pascal scripts have such switch, compiler directive, too. All users will be satisfied.

**Comment by carlokok** [comment]
Pull requests for a define that does this would certainly be accepted.

On 17 August 2016 19:43:01 CEST, ifermc <notifications@github.com> wrote:
>That would be really great if Pascal scripts have such switch, compiler
>directive, too. All users will be satisfied.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/remobjects/pascalscript/issues/141#issuecomment-240489341

-- 
Carlo Kok
RemObjects Software

**Comment by ifermc** [comment]
Now I realized that compiler option **PS_DELPHIDIV** is already in Pascal scripts! So, my problem can be easily solved by defining such option. No new pull request is necessary.

**Comment by neurolabusc** [comment]
I still think it would be great if "PS_DELPHIDIV" was defined by default for PascalScript. I do think many users who download PascalScript expect that divides will be float based.

**Comment by ifermc** [comment]
Fully agree. 
In meantime I also noticed that PS_DELHIDIV does not work properly when one or both variables are of variant type. Not only in the case of integers but also in the case of variants the result should be real number. This requires some more changes in uPSCompiler.GetResultType function, analogically INT-INT or REAL-INT or INT-REAL combinations.
