### ISSUE TITLE
X64 Windows Open Array Buffer Overrun

### ISSUE THREAD

**Issue by pleriche** [remobjects/pascalscript#151]
There are potential buffer overruns in the InitializeVariant procedure in the uPSRuntime unit when compiled for 64-bit.

Line 1780 is currently:
`        Pointer(Pointer(IPointer(p)+(2*PointerSize))^) := nil;`
but should be:
`        LongBool(Pointer(IPointer(p)+(2*PointerSize))^) := False;`

Line 1786 is currently:
`        Pointer(Pointer(IPointer(p)+(2*PointerSize))^) := nil;`
but should be:
`        Cardinal(Pointer(IPointer(p)+(2*PointerSize))^) := 0;`

These changes bring InitializeVariant in line with TPSTypeRec.CalcSize. Without these changes FastMM reports a buffer overrun under FullDebugMode when using open arrays (when compiled with the 64-bit compiler). This may be related to issue #150.

**Comment by evgeny-k** [comment]
thx. fixed

**Comment by pleriche** [comment]
I've since encountered more places that assume an element size of 24 under 64-bit (in contrast to TPSTypeRec.CalcSize that returns 20). In retrospect I think a better solution would be to increase the element size to 24 instead, since that does not lead to misaligned pointers in array entries. I've created a pull request for it.
