### ISSUE TITLE
crash on win32

### ISSUE THREAD

**Issue by User4martin** [remobjects/pascalscript#161]
On win32 calling a contstructor fails.  The reason is that the VMT is not correctly passed.

   function ClassCallProcConstructor(Caller: TPSExec; p: TPSExternalProcRec; Global, Stack: TPSStack): Boolean;

Source\uPSRuntime.pas  line 10250 

   {$IFnDEF PS_NOINT64}
   IntVal := CreateHeapVariant(Caller.FindType2(btS64));
   {$ELSE}
   IntVal := CreateHeapVariant(Caller.FindType2(btU32));
   {$ENDIF}

PS_NOINT64 is not defined, so the type is bts64.
But that means that in x86.inc it will not be passed as register.

I am not sure what the correct fix is here.

The following seems to work

   {$IFnDEF PS_NOINT64}
   {$IFDEF cpu32}
   IntVal := CreateHeapVariant(Caller.FindType2(btU32));
   {$ELSE}
   IntVal := CreateHeapVariant(Caller.FindType2(btS64));
   {$ENDIF}
   {$ELSE}
   IntVal := CreateHeapVariant(Caller.FindType2(btU32));
   {$ENDIF}

or should it be 

   {$IFDEF 32bit}

**Comment by carlokok** [comment]
hrmm but this code already looks like:

{$IFDEF CPU64}
  IntVal := CreateHeapVariant(Caller.FindType2(btS64));
  {$ELSE}
  IntVal := CreateHeapVariant(Caller.FindType2(btU32));
  {$ENDIF}

**Comment by User4martin** [comment]
Sorry, I didnt check careful enough.

Something must have gone wrong with my local merges.
