### ISSUE TITLE
unable to register type TDatasetErrorEvent

### ISSUE THREAD

**Issue by relativ** [remobjects/pascalscript#168]
Hello ,

When I implement db plugin to pascalscript I am gettin this error. "unable to register type TDatasetErrorEvent" when I check the codes the plugin has "cl.addTypeS('TDataSetErrorEvent', 'procedure (Dataset: TDataSet; E: TObject; var Action: TDataAction)');" this line code

can you please help me how to resolve this problem

**Comment by carlokok** [comment]
This means that, at the time you call this, TDataSet or TDataAction is unknown. Presuming those types are registered, your plugin runs too early?

**Comment by relativ** [comment]
resolved thanks
