### ISSUE TITLE
Implemented DBExpress components

### ISSUE THREAD

**Issue by relativ** [remobjects/pascalscript#169]
[uPSI_SqlExpr.zip](https://github.com/remobjects/pascalscript/files/1716425/uPSI_SqlExpr.zip)
Hello,

I am implementing dbx components packs but I can't get connection clearly. can you please check it

I sent you my dbx plugin as attached to this post.  And bottom of this content I write simple script to run by pascalscript. TSQLConnection object created as well but but it call Connected := true property then it exit by code. please check it

`Program IFSTest;
var
	SQLConnection: TSQLConnection;
	SQLQuery: TSQLQuery;
Begin
	SQLConnection:= TSQLConnection.Create(nil);
	SQLConnection.DriverName := 'MySQL';
	SQLConnection.ConnectionName := 'MySQLConnection';
	SQLConnection.LoginPrompt := false;
	SQLConnection.Params.Values['DriverName'] := 'MySQL';
	SQLConnection.Params.Values['Password'] := 'toor';
	SQLConnection.Params.Values['HostName'] := 'localhost';
	SQLConnection.Params.Values['Database'] := 'mysql';
	SQLConnection.Params.Values['User_Name'] := 'root';

	SQLConnection.Connected := true;
	SQLQuery:= TSQLQuery.Create(nil);
	SQLQuery.SQLConnection :=SQLConnection; 
	SQLQuery.SQL.Text := 'select * from user';
	SQLQuery.Open;
	while not SQLQuery.Eof do
	begin
               echo(SQLQuery.FieldByName('User').AsString);

		SQLQuery.Next;
	end;
	
	SQLQuery.Close();
	SQLQuery.Free(); 
	
	SQLConnection.Connected := false;
	SQLConnection.free();
	
End.`

**Comment by ronaldhoek** [comment]
This has probably nothing tot do with Pascal scripting, but with de availability of the drivers for DBX.
Can you put een tyr/except with an messagebox around the code en see what the actual error is?

It might be that DBX needs to be initialized in some way too, before you can use it as a plugin....
- I'm n DBX export, so I'm not sure about that
