### ISSUE TITLE
importing plugin help

### ISSUE THREAD

**Issue by relativ** [remobjects/pascalscript#174]
[db.zip](https://github.com/remobjects/pascalscript/files/1736034/db.zip)

Help please :( I tried every way to import plugin as a dll even I make interface to TPSPlugin class to return interface type but I am still getting same error.

this is i guess impotant bug I love pascalscript to use my opensource project but how to import plugin as a dll.

please help

**Comment by carlokok** [comment]
Again, please do NOT post duplicate issues.
