### ISSUE TITLE
TPicture methods doesn't work

### ISSUE THREAD

**Issue by relativ** [remobjects/pascalscript#175]
Hello,

I am trying to load image from file using image.picture.loadfromfile method but it cannot see loadfromfile method.

I added this two method in psr and psc component defining like
`RegisterMethod('procedure LoadFromFile(const FileName: string)');
    RegisterMethod('procedure SaveToFile(const FileName: string)');`

but it still dont work help please

**Comment by carlokok** [comment]
Pretty sure that if you call RegisterMethod it will at least let you call the mtehods. (you'd have to add it to the psr side too to actually make it work)

**Comment by carlokok** [comment]
Note that this is not a support forum; this is for bugreports.
