### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by relativ** [remobjects/pascalscript#176]
pascalscript working well for me thanks for it. but the problem is executing time errors. if error occured compiling time pascalscript shows me error message but if the error is in execution time doesn't do any thing. I just catch error with delphi debugger. for example "unknown picture file extension (jpg)" TImage doesn't support jpeg image its okey but pascalscript don't give me any error message.

thanks

**Comment by carlokok** [comment]
If the script has a try/except around the failure code it can properly catch it. If not it passes it on to the caller.

Note once again that this is NOT a support forum.
