### ISSUE TITLE
Not compatible with latest delphi version

### ISSUE THREAD

**Issue by larkonesvk** [remobjects/pascalscript#178]
Hi,
 i am currently using Delphi Tokyo 10.2 and i tried to compile this framework and i cant.

Unit uPSUtils gives error:
```
procedure TPSPascalParser.Next;
J := S[0]; // line number 1159 ... error incompatible types Char and AnsiChar

line number 1224 Left side cannot be assigned to
```
Will you provide another version of pascalscript for latest delphi??

Thanks

**Comment by evgeny-k** [comment]
I can't reproduce this with `Delphi 10.2 Version 25.0.29899.2631`.
```
Embarcadero Delphi for Win32 compiler version 32.0
Copyright (c) 1983,2017 Embarcadero Technologies, Inc.
..
88176 lines, 0.30 seconds, 549704 bytes code, 948 bytes data.
```
pls check that you haven't outdated `eDefines.inc`  in your search paths

**Comment by larkonesvk** [comment]
Yes you are right. My eDefines.inc was outdated. Thanks a lot
