### ISSUE TITLE
Code still uses ansistrings ?

### ISSUE THREAD

**Issue by DelphiniumCoin** [remobjects/pascalscript#185]
This seems to suck for new Delphi compatibility.

Any plans to make it completely work in unicode ?

Can re-compile scripts to output new byte code.

Rather have that then all kinds of ansistring vs unicode string compile and runtime problems I don't understand and are a lot of work to deal with solve, test, etc.

**Comment by carlokok** [comment]
reading this https://www.delphipraxis.net/198351-directions-arc-memory-management-delphi.html it looks like the upcoming delphi linux will be based on the traditional compilers that do support ansistrings. 

Once the new delphi is out we'll check if any work is needed and consider it then, but until it's really needed we won't port the code to avoid ansistrings.
