### ISSUE TITLE
I can't compile this code

### ISSUE THREAD

**Issue by relativ** [remobjects/pascalscript#188]
Hello,

Can you please help why I am taking this error.

Compiling
Compiler: [Error] (4:21): Identifier expected
Compiling failed

`program Test;

type
   TTestObject = class(TObject)
     procedure fetchdb;
   end;
      
      
  procedure TTestObject.fetchdb;
  begin
    writeqwqw('serkan');
  end;

var TestObject: TTestObject;

begin

  TestObject:= TTestObject.Create();
  TestObject.fetchdb();
end.
`

**Comment by carlokok** [comment]
Pascalscript does not support defining classes in code.
