### ISSUE TITLE
How to run Event in PascalScript?

### ISSUE THREAD

**Issue by luizluvizutto** [remobjects/pascalscript#230]
Hello friends!
I'm having difficulty running an event in PascalScript.
In this example, I have a "type" and a "class".

```
TEvento = procedure( txt: String );

TClassEvento = class( TComponent )
private
   FEvento: TEvento;
public
   property Evento: TEvento read FEvento write FEvento;
   procedure Executar;
end;

procedure ABC( msg: String );

implementation

procedure ABC( msg: String );
begin
   ShowMessage( msg ); 
end;

{ TClassEvento }

procedure TClassEvento.Executar;
begin
   if Assigned(FEvento) then begin
      FEvento( 'Olá Mundo' );
   end;
end;

procedure test;
var O: TClassEvento; 
begin
   O := TClassEvento.Create(NIL);
   try
      O.Evento := ABC;
      O.Executar;
   finally
      O.Free;
   end;
end;
```
With TEvento and TClassEvento registered in Pascal Script, as shown below:

```
procedure ABC( txt: String );
begin
   ShowMessage('Estou no Script: ' + txt);
end;

var O: TClassEvento; 
begin
   O := TClassEvento.Create(NIL);
   try
      O.Evento := @ABC;
      O.Executar;
   finally
      O.Free;
   end;
end.
```

*Comments:*
I saw in some grammars that you need to add the "@" `O.Evento: = @ABC;` when using PascalScript and does not work.
When I try to run without the "@" I get the return: **[Error] (10:22): Invalid number of parameters**

The [link](https://github.com/luizluvizutto/TstPascalScript) contains the example I set up.

Sorry for my English, I'm from Brazil and my sincere thanks.

**Comment by pult** [comment]
**? of object ?**
TEvento = procedure( txt: String ) **of object**;
```
...
procedure SIRegister_TClassEvento(CL: TPSPascalCompiler);
begin
  CL.AddTypeS('TEvento', 'procedure( txt: String )');
  with CL.AddClassN(CL.FindClass('TComponent'),'TClassEvento') do
  begin
    RegisterProperty('Evento', 'TEvento', iptrw);
...

```

**Comment by luizluvizutto** [comment]
I made the change and the same problem.

**Comment by pult** [comment]
I have no problems. Not enough information to analyze. Need a complete example, IDE version...

**Comment by luizluvizutto** [comment]
Hello, I'm using Delphi 10.3 Community Edition
Follow the link of the example I set up: [https://github.com/luizluvizutto/TstPascalScript](https://github.com/luizluvizutto/TstPascalScript)

**Comment by pult** [comment]
Working fine when correct your code:

**Un_Evento.pas**
`TEvento = procedure( txt: String ) of object; // changed declaration to method
`

**Un_Principal.pas**
```
TFrmPrincipal = class(TForm)
    ...
    procedure ProcedureDoEvento( txt: String ); // move to method
  end;
.,.
procedure TFrmPrincipal.ProcedureDoEvento( txt: String ); // implement as method
..

```

**Comment by luizluvizutto** [comment]
My problem is in the Script.

Perhaps I am not able to explain my problem correctly, because my English is weak.

When I run "Run script"
nothing happens.

In this link I uploaded an exe of this example. If you click on "Run Script" the ABC method is not triggered.
[https://www.dropbox.com/sh/840au9t57xinvgs/AADxE1yfrlrx8aULBl_RVBtSa?dl=0](https://www.dropbox.com/sh/840au9t57xinvgs/AADxE1yfrlrx8aULBl_RVBtSa?dl=0)

**Comment by pult** [comment]
Detailed:
https://github.com/pult/TstPascalScript/commit/54838fd0c00896018f054d02e5e48e57aa74f649

**Comment by luizluvizutto** [comment]
@pult  thanks for the concern brother.

I cloned your sources and tested it. Did not work. Clicking the "Executar Script" button nothing happens.

Send me your compiled executable for testing.

**Comment by pult** [comment]
binary (xe3, dx10.3, dx10.4 x86, x64 ) abd full sources with thirdparty...
[TstPascalScript-pult-full_v2020.0605.0217.7z](https://mega.nz/file/VgVTRQyD#BdJgzPgwT196MBJDPTe5T1WXO91OYH-pDbHn8CmhAm8)

**Comment by luizluvizutto** [comment]
Hello friend, it looks like I'm getting close to the solution!

Your executables worked!

I replaced the "rps" fonts in my source "... \ pascalscript \ Source" and recompiled my system and it worked!

Now my question was, what is different about your sources that you don't have in the main repository?

And again, thanks for the help!

**Comment by pult** [comment]
https://github.com/pult/pascalscript

**Comment by luizluvizutto** [comment]
Hello Friend!
Well, first I want to congratulate you on the fork of remobjects and, above all, to make something that I think is very important for Script work.
Only I had some doubts. I even apologize for meddling.
Wouldn't these adjustments make it legal for RemObjects to implement their sources?

**Comment by relativ** [comment]
hi,

how you solve the problem ? i had same problem , can describe it ? i don't understand from the reading.

thanks
