### ISSUE TITLE
Invoke Null procedure encounter error "Could not call proc"

### ISSUE THREAD

**Issue by ccy** [remobjects/pascalscript#232]
Run the following script:

```pascal
var v: variant;
begin
  v := Null;
end.
```
prompt "Could not call proc" error in **Delphi 10.4**.  I didn't try other Delphi release.

This happen from commit 86a057c8

**Comment by pjrobin** [comment]
@evgeny-k ?

**Comment by jozunav** [comment]
the same error Delphi 10.4

**Comment by pjrobin** [comment]
found a fix: in invokeCall.inc function TPSExec.InnerfuseCall, result type variant is not implemented. adding the following code after line 188 fixed the issue:
```
      btVariant:
      begin
        PVariant(res.dta)^ := Invoke(Address,Args,SysCalConv,TypeInfo(Variant),False,IsConstr).AsVariant;
      end;
```
