### ISSUE TITLE
Incorrect IPointer type definition

### ISSUE THREAD

**Issue by zedxxx** [remobjects/pascalscript#233]
Now it defined as:
```
  {$IFDEF VER140UP}
    IPointer = NativeInt;
  {$ELSE}
    {$IFDEF CPUX64}
    IPointer = IntPtr;
    {$ELSE}
    {$IFDEF CPU64} IPointer = LongWord;{$ELSE}  IPointer = Cardinal;{$ENDIF}{$ENDIF}
  {$ENDIF}
```
and there are two problems:
- `NativeInt` is incorrectly defined in Delphi 2007 ( https://stackoverflow.com/questions/7630781 )
- Delphi 10.3.3 (win32 target) provide a lot of warnings about *"signed and unsigned types"*:

> [dcc32 Warning] uPSUtils.pas(786): W1024 Combining signed and unsigned types - widened both operands
------
Possible fix:
```
  {$IFDEF DELPHI2009UP}
    IPointer = NativeUInt;
  {$ELSE}
    IPointer = Cardinal;
  {$ENDIF}
```

**Comment by Vizit0r** [comment]
x64 and NativeUInt coming on from XE2 version, not 2009.
But in common thats correct.

Will update it.
