### ISSUE TITLE
uPSRuntime.pas(14346): E2099 Overflow in conversion or arithmetic operation

### ISSUE THREAD

**Issue by luizluvizutto** [remobjects/pascalscript#236]
Hello friends!

After pulling the update, it started to display the following error:

[dcc64 Error] uPSRuntime.pas(14346): E2099 Overflow in conversion or arithmetic operation
[dcc64 Fatal Error] uPSComponent.pas(1557): F2063 Could not compile used unit 'uPSRuntime.pas'
Failed

additional information: Delphi Community 10.3.3 and repository: [https://github.com/pult/pascalscript](https://github.com/pult/pascalscript)

Code snippet where the compiler stops
```
      end else begin
        {$IFNDEF PS_NOINT64}
        if res^.FType.BaseType <> btS64 then
        {$ENDIF}
        begin
          //CopyArrayContents(Pointer(Longint(Stack)-PointerSize2), @PPSVariantData(res)^.Data, 1, Res^.FType);
          {+}
          //CopyArrayContents(Pointer(Longint(Stack)-Longint(PointerSize2)), @PPSVariantData(res)^.Data, 1, Res^.FType);
          CopyArrayContents(PointerShift(Stack,-PointerSize2), @PPSVariantData(res)^.Data, 1, Res^.FType);
          {+.}
        end;
      end;
```

**Comment by pult** [comment]
[fixed](https://github.com/pult/pascalscript/commit/dd2549a5dc136e9d4943d2762c856fb21c195801)

**Comment by luizluvizutto** [comment]
It worked! Thank you
