### ISSUE TITLE
win64 problem with string

### ISSUE THREAD

**Issue by relativ** [remobjects/pascalscript#238]
hi,

i compile pascalscript to win64 machine with no problem but when i call a plugin i create, the plugin has string properties that properties doesn't work i receive unknown properties ProviderName like .

is pascalscript compatible with 64 bit machines ? and how can i fix this problem

**Comment by carlokok** [comment]
It should be. @evgeny-k ?

**Comment by evgeny-k** [comment]
@relativ yes, it is compatible. can you create a simple testcase that reproduces this issue, pls?

**Comment by jozunav** [comment]
procedure TForm1.Button1Click(Sender: TObject);
begin
  PSScript1.Script.text := 'begin ShowMessage(''Hello Wold!!!!''); end.';
  if PSScript1.Compile then
    if PSScript1.Execute then
    else
      ShowMessage('Error Script:' + PSScript1.ExecErrorToString)
  else
    ShowMessage(PSScript1.CompilerErrorToStr(0));
end;

procedure TForm1.PSScript1Compile(Sender: TPSScript);
begin
  Sender.AddFunction(@ShowMessage, 'procedure ShowMessage(msg: string))');
end;



//This code Fail unreconigze string
![2020-09-07 21_14_15-Project1 - Delphi 10 4 - Unit1  Running   Built](https://user-images.githubusercontent.com/7327250/92423447-25f8e380-f14f-11ea-8d6d-de268c45bad2.png)

**Comment by jozunav** [comment]
I Only compile same code on 10.4 and Fail with diferent string displayed

**Comment by evgeny-k** [comment]
by some reasons, string has Ansi encoding, i.e. this code works:
```
procedure ShowMessage1(msg: string);
begin
  showmessage(PAnsiChar(msg));
end;

procedure TForm111.Button1Click(Sender: TObject);
begin
  PSScript1.Script.text := 'begin ShowMessage1(''Hello Wold!!!!''); end.';
  if PSScript1.Compile then begin
    if PSScript1.Execute then
    else
      ShowMessage('Error Script:' + PSScript1.ExecErrorToString)
  end
  else
    ShowMessage(PSScript1.CompilerErrorToStr(0));
end;

procedure TForm111.PSScript1Compile(Sender: TPSScript);
begin
  Sender.AddFunction(@ShowMessage1, 'procedure ShowMessage1(msg: string))');
end;
```

**Comment by evgeny-k** [comment]
by some reasons, string has Ansi encoding, i.e. this code works:
```
procedure ShowMessage1(msg: string);
begin
  showmessage(PAnsiChar(msg));
end;

procedure TForm111.Button1Click(Sender: TObject);
begin
  PSScript1.Script.text := 'begin ShowMessage1(''Hello Wold!!!!''); end.';
  if PSScript1.Compile then begin
    if PSScript1.Execute then
    else
      ShowMessage('Error Script:' + PSScript1.ExecErrorToString)
  end
  else
    ShowMessage(PSScript1.CompilerErrorToStr(0));
end;

procedure TForm111.PSScript1Compile(Sender: TPSScript);
begin
  Sender.AddFunction(@ShowMessage1, 'procedure ShowMessage1(msg: string))');
end;
```

**Comment by evgeny-k** [comment]
by some reasons, string has Ansi encoding, i.e. this code works:
```
procedure ShowMessage1(msg: string);
begin
  showmessage(PAnsiChar(msg));
end;

procedure TForm111.Button1Click(Sender: TObject);
begin
  PSScript1.Script.text := 'begin ShowMessage1(''Hello Wold!!!!''); end.';
  if PSScript1.Compile then begin
    if PSScript1.Execute then
    else
      ShowMessage('Error Script:' + PSScript1.ExecErrorToString)
  end
  else
    ShowMessage(PSScript1.CompilerErrorToStr(0));
end;

procedure TForm111.PSScript1Compile(Sender: TPSScript);
begin
  Sender.AddFunction(@ShowMessage1, 'procedure ShowMessage1(msg: string))');
end;
```
