### ISSUE TITLE
Constans errors

### ISSUE THREAD

**Issue by jozunav** [remobjects/pascalscript#239]
procedure TForm1.Button1Click(Sender: TObject);
begin
PSScript1.Script.text := 'begin ShowMessage(''Hello Wold!!!!''); end.';
if PSScript1.Compile then
if PSScript1.Execute then
else
ShowMessage('Error Script:' + PSScript1.ExecErrorToString)
else
ShowMessage(PSScript1.CompilerErrorToStr(0));
end;

procedure TForm1.PSScript1Compile(Sender: TPSScript);
begin
![2020-09-07 21_14_15-Project1 - Delphi 10 4 - Unit1  Running   Built](https://user-images.githubusercontent.com/7327250/92425454-50e63600-f155-11ea-8c4f-4090a4e05738.png)

Sender.AddFunction(@ShowMessage, 'procedure ShowMessage(msg: string))');

**Comment by evgeny-k** [comment]
already fixed in #238
