### ISSUE TITLE
Encounter error when execute InputQuery in XE4

### ISSUE THREAD

**Issue by ccy** [remobjects/pascalscript#73]
I use InputQuery defined in unit uPSI_Dialogs.pas.  I am using XE4.

When I execute InputQuery in PascalScript, I encounter

"Exception: Length of value array must be >= length of prompt array"

I think it is due to InputQuery has 3 overloaded functions defined in vcl.Dialogs.pas:

function InputQuery(const ACaption: string; const APrompts: array of string; var AValues: array of string; CloseQueryFunc: TInputCloseQueryFunc = nil): Boolean; overload;

function InputQuery(const ACaption: string; const APrompts: array of string; var AValues: array of string; CloseQueryEvent: TInputCloseQueryEvent; Context: TObject = nil): Boolean; overload;

function InputQuery(const ACaption, APrompt: string; var Value: string): Boolean; overload;

How to make the InputQuery works in PascalScript using XE4?

**Comment by uschuster** [comment]
We have just find the same issue. I have a fix in mind and will provide a pull request likely tomorrow.
